export const SET_TOKEN_REQUEST = 'SET_TOKEN_REQUEST';
export const SET_TOKEN_SUCCESS = 'SET_TOKEN_SUCCESS';
export const SET_TOKEN_FAILURE = 'SET_TOKEN_FAILURE';

export const GET_TOKEN_REQUEST = 'GET_TOKEN_REQUEST';
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS';
export const GET_TOKEN_FAILURE = 'GET_TOKEN_FAILURE';

export const SET_JOURNAL_CUSTOMISATION_REQUEST =
  'SET_JOURNAL_CUSTOMISATION_REQUEST';
export const SET_JOURNAL_CUSTOMISATION_SUCCESS =
  'SET_JOURNAL_CUSTOMISATION_SUCCESS';
export const SET_JOURNAL_CUSTOMISATION_FAILURE =
  'SET_JOURNAL_CUSTOMISATION_FAILURE';

export const SET_USER_ACCOUNT_TYPE_REQUEST = 'SET_USER_ACCOUNT_TYPE_REQUEST';
export const SET_USER_ACCOUNT_TYPE_SUCCESS = 'SET_USER_ACCOUNT_TYPE_SUCCESS';
export const SET_USER_ACCOUNT_TYPE_FAILURE = 'SET_USER_ACCOUNT_TYPE_FAILURE';

export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAILURE = 'USER_LOGOUT_FAILURE';

/* SIGNUP */
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

/*  SIGNUP OTP VERIFICATION*/
export const OTP_VERIFY_SIGNUP_REQUEST = 'OTP_VERIFY_SIGNUP_REQUEST';
export const OTP_VERIFY_SIGNUP_SUCCESS = 'OTP_VERIFY_SIGNUP_SUCCESS';
export const OTP_VERIFY_SIGNUP_FAILURE = 'OTP_VERIFY_SIGNUP_FAILURE';

/* LOGIN */
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

/* FORGOT PASSWORD OTP SEND*/
export const OTP_SEND_FORGOT_PASSWORD_REQUEST =
  'OTP_SEND_FORGOT_PASSWORD_REQUEST';
export const OTP_SEND_FORGOT_PASSWORD_SUCCESS =
  'OTP_SEND_FORGOT_PASSWORD_SUCCESS';
export const OTP_SEND_FORGOT_PASSWORD_FAILURE =
  'OTP_SEND_FORGOT_PASSWORD_FAILURE';

/*  FORGOT PASSWORD OTP VERIFICATION*/
export const OTP_VERIFY_FORGOT_PASSWORD_REQUEST =
  'OTP_VERIFY_FORGOT_PASSWORD_REQUEST';
export const OTP_VERIFY_FORGOT_PASSWORD_SUCCESS =
  'OTP_VERIFY_FORGOT_PASSWORD_SUCCESS';
export const OTP_VERIFY_FORGOT_PASSWORD_FAILURE =
  'OTP_VERIFY_FORGOT_PASSWORD_FAILURE';

/* FORGOT PASSWORD */
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

/* CHANGE PASSWORD */
export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';

/* USER INFO */
export const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE';

/* USER PLAN UPDATE */
export const SET_MEMBER_PLAN_REQUEST = 'SET_MEMBER_PLAN_REQUEST';
export const SET_MEMBER_PLAN_SUCCESS = 'SET_MEMBER_PLAN_SUCCESS';
export const SET_MEMBER_PLAN_FAILURE = 'SET_MEMBER_PLAN_FAILURE';

export const CMS_CONTENT_REQUEST = 'CMS_CONTENT_REQUEST';
export const CMS_CONTENT_SUCCESS = 'CMS_CONTENT_SUCCESS';
export const CMS_CONTENT_FAILURE = 'CMS_CONTENT_FAILURE';

export const UPDATE_MODS_REQUEST = 'UPDATE_MODS_REQUEST';
export const UPDATE_MODS_SUCCESS = 'UPDATE_MODS_SUCCESS';
export const UPDATE_MODS_FAILURE = 'UPDATE_MODS_FAILURE';

export const GET_MODS_REQUEST = 'GET_MODS_REQUEST';
export const GET_MODS_SUCCESS = 'GET_MODS_SUCCESS';
export const GET_MODS_FAILURE = 'GET_MODS_FAILURE';

export const SAVE_JOURNAL_MOD_REQUEST = 'SAVE_JOURNAL_MOD_REQUEST';
export const SAVE_JOURNAL_MOD_SUCCESS = 'SAVE_JOURNAL_MOD_SUCCESS';
export const SAVE_JOURNAL_MOD_FAILURE = 'SAVE_JOURNAL_MOD_FAILURE';

export const SAVE_FOCUS_ST_MOD_REQUEST = 'SAVE_FOCUS_ST_MOD_REQUEST';
export const SAVE_FOCUS_ST_MOD_SUCCESS = 'SAVE_FOCUS_ST_MOD_SUCCESS';
export const SAVE_FOCUS_ST_MOD_FAILURE = 'SAVE_FOCUS_ST_MOD_FAILURE';

export const GET_MAIN_JOURNAL_REQUEST = 'GET_MAIN_JOURNAL_REQUEST';
export const GET_MAIN_JOURNAL_SUCCESS = 'GET_MAIN_JOURNAL_SUCCESS';
export const GET_MAIN_JOURNAL_FAILURE = 'GET_MAIN_JOURNAL_FAILURE';

export const GET_JOURNALS_REQUEST = 'GET_JOURNALS_REQUEST';
export const GET_JOURNALS_SUCCESS = 'GET_JOURNALS_SUCCESS';
export const GET_JOURNALS_FAILURE = 'GET_JOURNALS_FAILURE';

export const GET_FOCUS_ST_REQUEST = 'GET_FOCUS_ST_REQUEST';
export const GET_FOCUS_ST_SUCCESS = 'GET_FOCUS_ST_SUCCESS';
export const GET_FOCUS_ST_FAILURE = 'GET_FOCUS_ST_FAILURE';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAILURE = 'UPDATE_PASSWORD_FAILURE';

export const UPDATE_JOURNAL_CONTENT_REQUEST = 'UPDATE_JOURNAL_CONTENT_REQUEST';
export const UPDATE_JOURNAL_CONTENT_SUCCESS = 'UPDATE_JOURNAL_CONTENT_SUCCESS';
export const UPDATE_JOURNAL_CONTENT_FAILURE = 'UPDATE_JOURNAL_CONTENT_FAILURE';
