export const SET_USER_SPENDING_LIMIT_REQUEST =
  'SET_USER_SPENDING_LIMIT_REQUEST';
export const SET_USER_SPENDING_LIMIT_SUCCESS =
  'SET_USER_SPENDING_LIMIT_SUCCESS';
export const SET_USER_SPENDING_LIMIT_FAILURE =
  'SET_USER_SPENDING_LIMIT_FAILURE';

export const GET_USER_DETAILS_REQUEST = 'GET_USER_DETAILS_REQUEST';
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_FAILURE = 'GET_USER_DETAILS_FAILURE';
